name: audio_player
description: Audio player for flutter
version: 0.0.1
author:
homepage:

dependencies:
  uuid: ^1.0.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: co.westfort.audioplayer
    pluginClass: AudioplayerPlugin